project:
  type: website
  output-dir: docs

website:
  title: "Mysite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - quartomarkdown.qmd
      - githubpages.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



